// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_MroHkO7BTHLm8ujTEhU9VqxjA86_miA',
    appId: '1:290164681095:web:dd4a7111bee65bd2234b22',
    messagingSenderId: '290164681095',
    projectId: 'arafahhoneydb',
    authDomain: 'arafahhoneydb.firebaseapp.com',
    storageBucket: 'arafahhoneydb.appspot.com',
    measurementId: 'G-JBLS0S3J33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtt4KQM9hxlTx01rNDIqwx1V38Pkw01OQ',
    appId: '1:290164681095:android:3bd9337e7acc4bed234b22',
    messagingSenderId: '290164681095',
    projectId: 'arafahhoneydb',
    storageBucket: 'arafahhoneydb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVFXhVYA1F9IA-XLjXqRyPsCz8W7qXNUc',
    appId: '1:290164681095:ios:e6fa7e423fb3f89f234b22',
    messagingSenderId: '290164681095',
    projectId: 'arafahhoneydb',
    storageBucket: 'arafahhoneydb.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVFXhVYA1F9IA-XLjXqRyPsCz8W7qXNUc',
    appId: '1:290164681095:ios:9a0ae0f1f7064f94234b22',
    messagingSenderId: '290164681095',
    projectId: 'arafahhoneydb',
    storageBucket: 'arafahhoneydb.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseapp.RunnerTests',
  );
}
